FROM mhart/alpine-node:8
MAINTAINER Akvo Foundation <devops@akvo.org>

RUN apk add --no-cache build-base su-exec python cairo-dev pango-dev xz jpeg-dev git

WORKDIR "/lumen"

CMD [ "./run-as-user.sh", "./install-and-start.sh" ]
