FROM clojure:lein-2.7.1
MAINTAINER Akvo Foundation <devops@akvo.org>

RUN set -ex && \
    apt-get -qq update && \
    apt-get -qq install -y --no-install-recommends --no-install-suggests \
    gosu postgis gdal-bin curl postgresql-client-9.6 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["./import-and-run.sh"]
