FROM clojure:lein-2.8.1

RUN set -eux && \
    apt-get -qq update && \
    apt-get -qq install -y --no-install-recommends --no-install-suggests \
    runit postgis gdal-bin curl postgresql-client-9.6 && \
    useradd --create-home --home /home/akvo --shell /bin/bash --password akvo akvo && \
    cp -r /root/.lein /home/akvo/.lein && \
    chown akvo:akvo /home/akvo/.lein -R && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["./import-and-run.sh"]
