{
 "title": "Calls to auth-allowed-paths",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_auth_allowed_paths_bucket[10m])) by (le))\n",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_auth_allowed_paths_bucket[10m])) by (le))\n",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_auth_allowed_paths_count)"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_auth_allowed_paths_count[10m]))"
    }
   ]
  },
  {
   "title": "Apdex score (250 ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(app_auth_allowed_paths_bucket{le=\"2.5\"}[10m])) + sum(rate(app_auth_allowed_paths_bucket{le=\"7.5\"}[10m])) ) / 2 / sum(rate(app_auth_allowed_paths_bucket[10m])) * 10",
     "legendFormat": "value"
    }
   ]
  }
 ]
}