{
 "title": "lumen",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "color", "label": "color", "query": "label_values(color)" },
   {
    "name": "tenant",
    "label": "tenant",
    "query": "label_values(http_request_latency_seconds_bucket , tenant)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Request per second (2XX) ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{run=\"lumen-blue-green\", path!=\"/healthz\", statusClass=\"2XX\", color=~\"$color\", tenant=~\"$tenant\"}[$__interval])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "95% latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket{run=\"lumen-blue-green\", statusClass=\"2XX\", color=~\"$color\", tenant=~\"$tenant\"}[$__interval])) by (le,path,method))",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Request per second (errors)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{run=\"lumen-blue-green\", path!=\"\", statusClass!=\"2XX\"}[$__interval])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Restarts ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"lumen-[[color]].*\"}[$__interval])) by (pod, container)",
     "legendFormat": "{{pod}} - {{container}} "
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"lumen-[[color]].*\", container!=\"POD\", container=~\".+\"}[$__interval])) by (container, pod)\n",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 }, "options": { "content": "\n# DB stats\n\n\n\n\n" }, "content": "\n# DB stats\n\n\n\n\n" },
  {
   "title": "Threads waiting for a connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"[[tenant]].*PendingConnections\", run=\"lumen-blue-green\", color=~\"$color\"}  ",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "For how long a DB connection is used (95% percentile)",
   "type": "graph",
   "description": "Time that a DB connection has been in use, from the point of acquiring it from the pool, to the point returning it back.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"[[tenant]].*Usage\", run=\"lumen-blue-green\", color=~\"$color\", quantile=\"0.95\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "How long it takes to adquire a DB connection (95% percentile)",
   "type": "graph",
   "description": "Time to acquire a connection from the connection pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"[[tenant]].*Wait\", run=\"lumen-blue-green\", color=~\"$color\", quantile=\"0.95\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "How long to create a new DB connection(95% percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"[[tenant]].*ConnectionCreation\", run=\"lumen-blue-green\", color=~\"$color\", quantile=\"0.95\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 }, "options": { "content": "\n# Memory stats\n\n\n\n\n" }, "content": "\n# Memory stats\n\n\n\n\n" },
  {
   "title": "Memory (MiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"lumen-[[color]].*\", container!=\"POD\", container=~\".+\"} / 1024 / 1024",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{run=\"lumen-blue-green\", color=~\"${color}\"}",
     "legendFormat": "{{area}} memory [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_memory_bytes_max{run=\"lumen-blue-green\", color=~\"${color}\"}",
     "legendFormat": "max {{area}} memory [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "GC time spend per second",
   "type": "graph",
   "description": "See https://www.robustperception.io/irate-graphs-are-better-graphs and https://medium.com/@valyala/why-irate-from-prometheus-doesnt-capture-spikes-45f9896d7832 to understand the difference between rate and irate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{run=\"lumen-blue-green\", color=~\"${color}\"}[$__interval]))",
     "legendFormat": "rate"
    },
    {
     "expr": "sum(irate(jvm_gc_collection_seconds_sum{run=\"lumen-blue-green\", color=~\"${color}\"}[$__interval]))",
     "legendFormat": "irate"
    }
   ]
  }
 ]
}