{
 "title": "Lumen Flow API Authz",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "color", "label": "color", "query": "label_values(color)" },
   {
    "name": "tenant",
    "label": "tenant",
    "query": "label_values(app_load_auth_data_bucket, tenant)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "## All graphs have an $interval average\n\n\n\n"
  },
  {
   "title": "Load auth data 95% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_load_auth_data_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Load auth data 99% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_load_auth_data_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(app_load_auth_data_count{color=~\"$color\"}[$interval])) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_load_auth_data_count{color=~\"$color\"}) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Authz HTTP calls 95% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_flow_check_permissions_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Authz HTTP calls 99% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_flow_check_permissions_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth dataset 95% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_auth_datasets_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth dataset 99% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_auth_datasets_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth viz 95% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_auth_visualisations_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth viz 99% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_auth_visualisations_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth dashboard 95% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_auth_dashboards_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth dashboards 99% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_auth_dashboards_bucket{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Auth collections 95% latency per tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_auth_collections{color=~\"$color\"}[$interval])) by (le,tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Load auth data apdex score (2.5 secs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(app_load_auth_data_bucket{le=\"2.5\",color=~\"$color\"}[$interval])) by (tenant) + sum(rate(app_load_auth_data_bucket {le=\"7.5\",color=~\"$color\"}[$interval])) by (tenant)) / 2 / sum(rate(app_flow_check_permissions_count{color=~\"$color\"}[$interval])) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  }
 ]
}