export const CREATE = 'DASHBOARD_CREATE';
export const EDIT = 'DASHBOARD_EDIT';

export const CREATE_DASHBOARD_REQUEST = 'DASHBOARD_CREATE_REQUEST';
export const CREATE_DASHBOARD_SUCCESS = 'DASHBOARD_CREATE_SUCCESS';
export const CREATE_DASHBOARD_FAILURE = 'DASHBOARD_CREATE_FAILURE';

export const FETCH_DASHBOARDS_SUCCESS = 'DASHBOARDS_FETCH_SUCCESS';

export const FETCH_DASHBOARD_REQUEST = 'DASHBOARD_FETCH_REQUEST';
export const FETCH_DASHBOARD_SUCCESS = 'DASHBOARD_FETCH_SUCCESS';
export const FETCH_DASHBOARD_FAILURE = 'DASHBOARD_FETCH_FAILURE';

// Delete dashboard
export const DELETE_DASHBOARD_REQUEST = 'DASHBOARD_DELETE_REQUEST';
export const DELETE_DASHBOARD_FAILURE = 'DASHBOARD_DELETE_FAILURE';
export const DELETE_DASHBOARD_SUCCESS = 'DASHBOARD_DELETE_SUCCESS';
export const REMOVE_DASHBOARD = 'DASHBOARD_REMOVE';
