export const CREATE = 'VISUALISATION_CREATE';
export const EDIT = 'VISUALISATION_EDIT';

export const CREATE_VISUALISATION_REQUEST = 'VISUALISATION_CREATE_REQUEST';
export const CREATE_VISUALISATION_SUCCESS = 'VISUALISATION_CREATE_SUCCESS';
export const CREATE_VISUALISATION_FAILURE = 'VISUALISATION_CREATE_FAILURE';

export const FETCH_VISUALISATIONS_SUCCESS = 'VISUALISATIONS_FETCH_SUCCESS';

export const FETCH_VISUALISATION_REQUEST = 'VISUALISATION_FETCH_REQUEST';
export const FETCH_VISUALISATION_SUCCESS = 'VISUALISATION_FETCH_SUCCESS';
export const FETCH_VISUALISATION_FAILURE = 'VISUALISATION_FETCH_FAILURE';
