FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -yq \
    vim locales

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Install required packages

RUN apt-get update && \
  apt-get install -yq \
  build-essential \
  curl \
  git \
  libmapnik-dev \
  pkg-config \
  python-dev \
  libcairo2-dev \
  libjpeg-dev \
  libpango1.0-dev \
  libgif-dev \
  g++

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 6.11.1

RUN curl -o- \
    https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh \
    | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN node --version
RUN npm --version

RUN npm install nodemon -g

# Debugging mode on
ENV NODE_ENV development

EXPOSE 4000

# Start server
CMD cd /tiler && make && nodemon --inspect ./server.js